# Generated by Django 2.2.2 on 2019-07-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
